name: minimal
description: A minimalistic Flutter website template for blogs and portfolios.
version: 2.0.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
#  responsive_framework:
#    path: ../
  # Uncomment to build standalone project.
  responsive_framework: ^1.4.0
  google_fonts: ^6.2.1
  animations: ^2.0.11
  loading_gifs: ^0.3.0
  url_launcher: ^6.3.0 # Requires setup.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/Minimal-Logo.png"
  image_path_android: "assets/Minimal-Logo.png"
  image_path_ios: "assets/Minimal-Logo-iOS.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/Minimal-Logo-Adaptive.png"
  web:
    generate: true
  macos:
    generate: true
  windows:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/