name: minimal
description: A minimalistic Flutter website template for blogs and portfolios.
version: 1.0.3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^0.0.7
  google_fonts: ^1.0.0
  animations: ^1.0.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/Minimal-Logo.png"
  image_path_ios: "assets/Minimal-Logo-iOS.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/Minimal-Logo-Adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/