name: Build HTML

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: stable
      - name: Clone deployment repo
        run: |
          git clone --single-branch "https://${{ secrets.PAT }}@github.com/searchy2/Demo.git" "clone_dir"
          rm -rf clone_dir/flutterwebsites/minimal-html/
          mkdir -p clone_dir/flutterwebsites/minimal-html/
      - name: Build
        run: |
          flutter build web --release --base-href /flutterwebsites/minimal-html/ --web-renderer html
          mv build/web/* clone_dir/flutterwebsites/minimal-html
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Get time in seconds
        id: seconds
        run: echo "::set-output name=seconds::$(date +'%s')"
      - name: Push build commit
        run: |
          cd clone_dir
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *
          git commit -m "Build Minimal HTML ${{ steps.date.outputs.date }} (${{ steps.seconds.outputs.seconds }})"
          git pull --rebase
          git push
